server:
  port: 8081

logging:
  file:
    name: ../logs/


spring:
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    # 开发时关闭缓存
    cache: false
    suffix: .html
    encoding: utf-8
    servlet:
      content-type: text/html
    mode: HTML5

#  datasource:
#    url: jdbc:mysql://localhost:3306/testuserlist?serverTimezone=GMT%2B8
#    username: root
#    password: mysql12
#    driver-class-name: com.mysql.cj.jdbc.Driver
#mybatis:
#  config-location: classpath:SqlMapConfig.xml
#  mapper-locations: classpath:com/meng/dao/*.xml
#  type-aliases-package: com.meng.entity
